services:
  postgres:
    image: postgres:18
    container_name: postgres-${POSTGRES_DB}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
      PGTZ: ${PGTZ}
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - pg_network
    ports:
      - "5432:5432"

networks:
  pg_network:
    name: pg_network
    driver: bridge